name: Unittest

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - LICENSE
      - '**.md'
      - .gitignore
      - .editorconfig
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  unittest:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-11

    steps:
      - uses: actions/checkout@v5

      - name: Download environment file
        run: |
          wget https://raw.githubusercontent.com/iSnobal/model_setup/refs/heads/main/conda/isnobal.yaml

      - name: Install and set GCC 11 as default on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11
          # Update alternatives for system-wide default
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-11 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-11 100
          # Check
          gcc --version
          g++ --version
        shell: bash

      - name: Install and set GCC 11 as default on macOS
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install gcc@11
          # Symlink gcc-11 as gcc to ensure default in path
          ln -sf $(brew --prefix)/opt/gcc@11/bin/gcc-11 /usr/local/bin/gcc
          ln -sf $(brew --prefix)/opt/gcc@11/bin/g++-11 /usr/local/bin/g++
          # Check
          gcc --version
          g++ --version
        shell: bash

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: isnobal.yaml
          init-shell: bash
          cache-environment: true

      - name: Run unittests
        run: |
          micromamba run -n isnobal make install
          micromamba run -n isnobal make tests
